config:
  nexodo-infra:location: eastus
  nexodo-infra:minReplicas: "1"
  nexodo-infra:maxReplicas: "3"
  nexodo-infra:cpuCores: "0.5"
  nexodo-infra:memorySize: 1.0Gi
  nexodo-infra:resourceGroupName: nexodo-rg
  nexodo-infra:containerRegistryName: nexodoacr
  nexodo-infra:environmentName: nexodo-env
  nexodo-infra:containerAppName: nexodo-app
  nexodo-infra:dataStorageAccountName: nexodo
  # Secrets should be set via: pulumi config set --secret <key> <value>
  # Or via GitHub Actions using environment variables
